spring:
  application:
    name: feedbacker

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/feedbacker}
    username: ${DB_USERNAME:feedbacker}
    password: ${DB_PASSWORD:feedbacker_local_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: ${PORT:8080}

supabase:
  url: ${SUPABASE_URL:}
  storage:
    secret-key: ${SUPABASE_SECRET_KEY:}
    bucket: ${SUPABASE_STORAGE_BUCKET:}
