CREATE TABLE member (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    nickname VARCHAR(10) UNIQUE,
    role VARCHAR(20),
    provider VARCHAR(20) NOT NULL,
    provider_id VARCHAR(255),
    profile_image VARCHAR(512),
    portfolio_link VARCHAR(512),
    humidity NUMERIC(5, 2) NOT NULL DEFAULT 30.00,
    grade VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    deactivated_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_member_provider_provider_id UNIQUE (provider, provider_id)
);

CREATE TABLE member_interest (
    member_id UUID NOT NULL,
    interest_order INTEGER NOT NULL,
    interest VARCHAR(20) NOT NULL,
    PRIMARY KEY (member_id, interest_order),
    CONSTRAINT fk_member_interest_member FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE TABLE acorn_wallet (
    member_id UUID PRIMARY KEY,
    balance INTEGER NOT NULL,
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_acorn_wallet_member FOREIGN KEY (member_id) REFERENCES member (id)
);

CREATE TABLE refresh_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID NOT NULL,
    token VARCHAR(512) NOT NULL UNIQUE,
    expires_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_refresh_token_member ON refresh_token (member_id);

CREATE TABLE email_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    sent_at TIMESTAMP(6) NOT NULL,
    verified BOOLEAN NOT NULL,
    verified_until TIMESTAMP(6),
    failed_attempts INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE project (
    project_id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(2048) NOT NULL,
    service_link VARCHAR(255) NOT NULL,
    thumbnail_image VARCHAR(255) NOT NULL,
    view_count BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_project_owner FOREIGN KEY (owner_id) REFERENCES member (id)
);

CREATE TABLE project_tags (
    project_id UUID NOT NULL,
    tag_order INTEGER NOT NULL,
    tag VARCHAR(20) NOT NULL,
    PRIMARY KEY (project_id, tag_order),
    CONSTRAINT fk_project_tags_project FOREIGN KEY (project_id) REFERENCES project (project_id)
);

CREATE TABLE feedback_posts (
    feedback_post_id UUID PRIMARY KEY,
    writer_id UUID NOT NULL,
    writer_name VARCHAR(255) NOT NULL,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(255) NOT NULL,
    target_type VARCHAR(255) NOT NULL,
    service_url VARCHAR(2048),
    images JSONB,
    slot_capacity INTEGER NOT NULL,
    remain_slot_count INTEGER NOT NULL,
    deposit_acorn INTEGER NOT NULL,
    reward_acorn INTEGER NOT NULL,
    start_at TIMESTAMP(6) NOT NULL,
    end_at TIMESTAMP(6) NOT NULL,
    project_id UUID NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_feedback_posts_project FOREIGN KEY (project_id) REFERENCES project (project_id)
);

CREATE TABLE questions (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_post_id UUID NOT NULL,
    question_type VARCHAR(20) NOT NULL,
    question_order INTEGER NOT NULL,
    required BOOLEAN NOT NULL,
    question_text VARCHAR(500) NOT NULL,
    images JSONB,
    max_selection_count INTEGER,
    minimum_length INTEGER,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_questions_feedback_post FOREIGN KEY (feedback_post_id) REFERENCES feedback_posts (feedback_post_id)
);

-- No @OrderColumn is declared for this collection in Question.
CREATE TABLE question_options (
    question_id BIGINT NOT NULL,
    option_text VARCHAR(255),
    CONSTRAINT fk_question_options_question FOREIGN KEY (question_id) REFERENCES questions (question_id)
);

CREATE TABLE participations (
    participation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_post_id UUID NOT NULL,
    tester_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    reserved_at TIMESTAMP(6) NOT NULL,
    submission_deadline_at TIMESTAMP(6) NOT NULL,
    abandoned_at TIMESTAMP(6),
    expired_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_participation_post_tester UNIQUE (feedback_post_id, tester_id),
    CONSTRAINT fk_participations_feedback_post FOREIGN KEY (feedback_post_id) REFERENCES feedback_posts (feedback_post_id),
    CONSTRAINT fk_participations_tester FOREIGN KEY (tester_id) REFERENCES member (id)
);

CREATE INDEX idx_participation_tester ON participations (tester_id);
CREATE INDEX idx_participation_post_status ON participations (feedback_post_id, status);
CREATE INDEX idx_participation_deadline_status ON participations (submission_deadline_at, status);

CREATE TABLE feedbacks (
    feedback_id UUID PRIMARY KEY,
    feedback_post_id UUID NOT NULL,
    tester_id UUID NOT NULL,
    tester_name VARCHAR(255),
    post_title VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    reward_acorn INTEGER,
    reject_type VARCHAR(255),
    reject_detail TEXT,
    object_reason TEXT,
    submit_at TIMESTAMP(6) NOT NULL,
    expire_at TIMESTAMP(6) NOT NULL,
    processed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE question_answers (
    question_answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id UUID NOT NULL,
    question_id BIGINT NOT NULL,
    question_order INTEGER NOT NULL,
    images JSONB,
    selected_option INTEGER[],
    subjective_answer TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_answer_feedback_question UNIQUE (feedback_id, question_id),
    CONSTRAINT fk_question_answers_feedback FOREIGN KEY (feedback_id) REFERENCES feedbacks (feedback_id)
);

CREATE TABLE acorn_history (
    acorn_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id UUID NOT NULL,
    feedback_post_id UUID,
    feedback_id UUID,
    type VARCHAR(255) NOT NULL,
    translate_at TIMESTAMP(6) NOT NULL,
    change_acorn INTEGER NOT NULL,
    CONSTRAINT fk_acorn_history_member FOREIGN KEY (member_id) REFERENCES member (id)
);
